src/Entity/Box.php
<?php

/**
 * This file is part of the Organizer package.
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BoxRepository")
 * @ORM\Table(name="box",uniqueConstraints={@ORM\UniqueConstraint(name="box_number_uniq", columns={"box_number"})})
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class Box extends AbstractEntity implements EntityInterface
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BoxModel", inversedBy="boxes")
     */
    protected $boxModel;

    /**
     * @ORM\Column(type="integer")
     */
    protected $boxNumber;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $label;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="boxes")
     */
    protected $location;

    /**
     * @ORM\PrePersist
     */
    public function generateBoxNumber(LifecycleEventArgs $event): void
    {
        if (isset($this->boxNumber)) {
            return;
        }

        $this->boxNumber = $event->getEntityManager()->getRepository(Box::class)->getNextBoxNumber();
    }

    public function getBoxModel(): ?BoxModel
    {
        return $this->boxModel;
    }

    public function getBoxNumber(): ?int
    {
        return $this->boxNumber;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getDisplayId(): string
    {
        return empty($this->getBoxNumber()) ? '' : sprintf('%04d', $this->getBoxNumber());
    }

    public function getDisplayLabel(): string
    {
        return empty($this->getBoxNumber()) ? $this->getLabel() : sprintf('Box %04d - %s', $this->getBoxNumber(), $this->getLabel());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    /**
     * Checks to see if a box should be hidden from searches.
     */
    public function isHidden(): bool
    {
        $location = $this->getLocation();
        if ($location === null) {
            return false;
        }

        return $location->getHideFromSearch();
    }

    public function setBoxModel(?BoxModel $boxModel): self
    {
        $this->boxModel = $boxModel;

        return $this;
    }

    public function setBoxNumber(int $boxNumber): self
    {
        $this->boxNumber = $boxNumber;

        return $this;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description ?? '';

        return $this;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }
}

src/Form/BoxType.php
<?php

/**
 * This file is part of the Organizer package.
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form;

use App\Entity\Box;
use App\Entity\BoxModel;
use App\Entity\Location;
use App\Repository\BoxModelRepository;
use App\Repository\LocationRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Builds a form for editing a box
 */
class BoxType extends AbstractType
{
    /**
     * Constructor
     */
    public function __construct(
        protected BoxModelRepository $boxModelRepository,
        protected LocationRepository $locationRepository
    ) {
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('label')
            ->add('description')
            ->add(
                'location',
                EntityType::class,
                [
                    'choice_label' => 'displayLabel',
                    'class'        => Location::class,
                    'choices'      => $this->locationRepository->getSortedByDisplayLabel(),
                    'placeholder'  => 'Choose a location...',
                    'required'     => false,
                ]
            )
            ->add(
                'boxModel',
                EntityType::class,
                [
                    'choice_label' => 'label',
                    'class'        => BoxModel::class,
                    'choices'      => $this->boxModelRepository->getSortedByDisplayLabel(),
                    'placeholder'  => 'Choose a model...',
                    'required'     => false,
                ]
            )
            ->add('save', SubmitType::class);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Box::class,
        ]);
    }
}

src/Controller/BoxController.php
<?php

/**
 * This file is part of the Organizer package.
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Controller;

use App\Entity\Box;
use App\Entity\BoxModel;
use App\Entity\Location;
use App\Form\BoxType;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Controller for /box
 */
class BoxController extends AbstractController
{
    use CrudTrait;

    /**
     * Session index for controlling new box behavior.
     */
    protected const SESSION_NEW_BOX = 'nübox';

    /**
     * Options that renderCustomForm uses
     *
     * @var array
     */
    protected $formOptions = [
        'formClass'    => BoxType::class,
        'successRoute' => 'app_box_recent',
        'template'     => 'box/index.html.twig',
    ];

    /**
     * Constructs a new Box controller
     */
    public function __construct(protected EntityManagerInterface $em)
    {
    }

    #[Route(path: '/box/{id}', name: 'app_box', requirements: ['id' => '\d+'])]
    public function index(Request $request, int $id)
    {
        return $this->renderCustomForm($this->em, [
            'entity'          => $this->em->getRepository(Box::class)->findOneById($id),
            'request'         => $request,
            'successCallback' => fn($entity) => 'Updated ' . $entity->getDisplayLabel(),
        ]);
    }

    #[Route(path: '/box/new', name: 'app_box_new')]
    public function new(Request $request)
    {
        $session = $request->getSession();

        $session->set(static::SESSION_NEW_BOX, false);

        return $this->renderCustomForm($this->em, [
            'entity'          => new Box(),
            'request'         => $request,
            'successCallback' => fn() => 'Box created successfully.',
            'successRoute'    => null,
            'successRouteCallback' => function ($entity) use ($session) {
                $session->set(static::SESSION_NEW_BOX, true);
                return $this->redirectToRoute('app_box_search_id', ['id' => $entity->getId()]);
            },
        ]);
    }

    #[Route(path: '/box/search', name: 'app_box_search')]
    public function search(Request $request): Response
    {
        $query = $request->get('q');
        $boxes = $this->em->getRepository(Box::class)->findByKeyword($query);
        return $this->render(
            'box/search.html.twig',
            [
                'boxes'  => $boxes,
                'query'  => $query,
                'type'   => null,
            ]
        );
    }

    #[Route(path: '/box/search/id/{id}', name: 'app_box_search_id', requirements: ['id' => '\d+'])]
    public function searchById(Request $request, int $id)
    {
        $session = $request->getSession();

        $entity = $this->em->getRepository(Box::class)->find($id);
        if (!is_object($entity)) {
            $this->addFlash('error', 'Unable to show box ' . $id);
            return $this->redirectToRoute('app_home');
        }

        $hideMessage = $session->get(static::SESSION_NEW_BOX, false);
        $session->remove(static::SESSION_NEW_BOX);

        return $this->render(
            'box/search.html.twig',
            [
                'boxes'       => [$entity],
                'entity'      => $entity,
                'type'        => 'Box',
                'hideMessage' => $hideMessage,
            ]
        );
    }

    #[Route(path: '/box/search/location/{id}', name: 'app_box_search_location', requirements: ['id' => '\d+'])]
    public function searchByLocation(int $id)
    {
        $entity = $this->em->getRepository(Location::class)->find($id);
        if (!is_object($entity)) {
            $this->addFlash('error', 'Unable to show boxes for invalid location ' . $id);
            return $this->redirectToRoute('app_home');
        }

        return $this->render(
            'box/search.html.twig',
            [
                'boxes'  => $entity->getBoxes(),
                'entity' => $entity,
                'type'   => 'Location',
            ]
        );
    }

    #[Route(path: '/box/search/model/{id}', name: 'app_box_search_model', requirements: ['id' => '\d+'])]
    public function searchByModel(int $id)
    {
        $entity = $this->em->getRepository(BoxModel::class)->find($id);
        if (!is_object($entity)) {
            $this->addFlash('error', 'Unable to show boxes for invalid box model ' . $id);
            return $this->redirectToRoute('app_home');
        }

        return $this->render(
            'box/search.html.twig',
            [
                'boxes'  => $entity->getBoxes(),
                'entity' => $entity,
                'type'   => 'BoxModel',
            ]
        );
    }

    #[Route(path: '/box/showAll', name: 'app_box_all')]
    public function showAll(): Response
    {
        return $this->render(
            'box/all.html.twig',
            [
                'boxes' => $this->em->getRepository(Box::class)->getSortedByDisplayLabel(),
                'title' => 'All Boxes',
            ]
        );
    }


    /**
     * @throws Exception
     */
    #[Route(path: '/box/recent', name: 'app_box_recent')]
    public function showRecent(): Response
    {
        return $this->render(
            'box/all.html.twig',
            [
                'boxes' => $this->em->getRepository(Box::class)->getRecent('-30 days'),
                'title' => 'Boxes Added or Changed Over the Past 30 Days',
            ]
        );
    }
}

templates/box/all.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/box_card.html.twig' as boxCard %}

{% block title %}
    Organizer: All Boxes
{% endblock %}

{% block body %}
    <div class="row mb-3">
        <div class="col text-center">
            {{ title }}
        </div>
    </div>
    {% for row in boxes|batch(3, 'skip') %}
        <div class="row mb-lg-3">
            {% for box in row %}
                <div class="col-12 col-lg-4">
                    {% if box != 'skip' %}
                        {{ boxCard.draw(box, true, true) }}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

templates/box/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Organizer: {{ entity.label }}
{% endblock %}

{% block body %}
    <div class="row mb-3 text-center">
        <div class="col">
            {% if entity.id is not null %}
                <h4>{{ entity.displayLabel }}</h4>
            {% else %}
                <h4>New Box</h4>
            {% endif %}
        </div>
    </div>
    {% if entity.id is not null %}
        <div class="mb-3">
            <label for="boxNumber">Box Number</label>
            <input type="text" class="form-control" disabled id="boxNumber" placeholder="Automatically Assigned" value="{{ entity.displayId | e('html_attr') }}">
        </div>
    {% endif %}
    {{ form(form) }}
{% endblock %}

templates/box/search.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/box_card.html.twig' as boxCard %}

{% block title %}
    Organizer: Search Results
{% endblock %}

{% block body %}
    {% if hideMessage is not defined or hideMessage is empty %}
        <div class="row mb-3">
            <div class="col">
                <div class="p-3 mb-2 bg-secondary text-white">
                    {% if entity is defined %}
                        {% if type == 'BoxModel' %}
                            Showing boxes for Box Model: {{ entity.label }}
                        {% elseif type == 'Location' %}
                            Showing boxes for Location: {{ entity.displayLabel }}
                        {% elseif type == 'Box' %}
                            Showing Box {{ entity.displayId }}
                        {% endif %}
                    {% else %}
                        Search results for "{{ query }}"
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
    {% if boxes is not empty %}
        {% for row in boxes|batch(3, 'skip') %}
            <div class="row mb-lg-3">
                {% for box in row %}
                    <div class="col-12 col-lg-4">
                        {% if box != 'skip' %}
                            {{ boxCard.draw(box, type != 'Location', type != 'BoxModel') }}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <div class="row mb-3">
            <div class="col">
                <div class="p-3 mb-2 bg-danger text-white">
                    No results found
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}