src/Entity/Box.php
<?php

/**
 * This file is part of the Organizer package.
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BoxRepository")
 * @ORM\Table(name="box",uniqueConstraints={@ORM\UniqueConstraint(name="box_number_uniq", columns={"box_number"})})
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class Box extends AbstractEntity implements EntityInterface
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BoxModel", inversedBy="boxes")
     */
    protected $boxModel;

    /**
     * @ORM\Column(type="integer")
     */
    protected $boxNumber;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $label;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="boxes")
     */
    protected $location;

    /**
     * @ORM\PrePersist
     */
    public function generateBoxNumber(LifecycleEventArgs $event): void
    {
        if (isset($this->boxNumber)) {
            return;
        }

        $this->boxNumber = $event->getEntityManager()->getRepository(Box::class)->getNextBoxNumber();
    }

    public function getBoxModel(): ?BoxModel
    {
        return $this->boxModel;
    }

    public function getBoxNumber(): ?int
    {
        return $this->boxNumber;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getDisplayId(): string
    {
        return empty($this->getBoxNumber()) ? '' : sprintf('%04d', $this->getBoxNumber());
    }

    public function getDisplayLabel(): string
    {
        return empty($this->getBoxNumber()) ? $this->getLabel() : sprintf('Box %04d - %s', $this->getBoxNumber(), $this->getLabel());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    /**
     * Checks to see if a box should be hidden from searches.
     */
    public function isHidden(): bool
    {
        $location = $this->getLocation();
        if ($location === null) {
            return false;
        }

        return $location->getHideFromSearch();
    }

    public function setBoxModel(?BoxModel $boxModel): self
    {
        $this->boxModel = $boxModel;

        return $this;
    }

    public function setBoxNumber(int $boxNumber): self
    {
        $this->boxNumber = $boxNumber;

        return $this;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description ?? '';

        return $this;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }
}

src/Entity/User.php
<?php

/**
 * This file is part of the Organizer package.
 *
 * (c) Doug Harple <dharple@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Utility\Gravatar;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false, hardDelete=true)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;
    use SoftDeleteableEntity;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email = null;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     *
     * @phpstan-ignore-next-line
     */
    private $id;

    /**
     * The hashed password
     *
     * @ORM\Column(type="string")
     */
    private ?string $password = null;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * Returns an avatar URL
     */
    public function getAvatarUrl(): string
    {
        return Gravatar::getAvatarUrl($this->getEmail());
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @see UserInterface
     *
     * @return ?string
     */
    public function getSalt(): ?string
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

templates/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Organizer: About
{% endblock %}

{% block body %}
    <div class="row mb-3 text-center">
        <div class="col">
            <h4>About</h4>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <p>Organizer is a tool for keeping track of storage boxes.</p>

            <p>This site is built with <a href="https://symfony.com/license"
            target="_blank">Symfony</a> with help from its <a
            href="https://symfony.com/doc/master/contributing/documentation/license.html"
            target="_blank">documentation</a>.</p>

            <p>This site is built using <a
            href="https://getbootstrap.com/docs/5.3/about/license/"
            target="_blank">Bootstrap</a>.</p>

            <p>Thanks to <a href="https://fontawesome.com/license/free"
            target="_blank">Font Awesome</a> for the use of their icons.  I
            modified the dolly icon seen in the site icon.</p>
        </div>
    </div>
{% endblock %}

templates/allBoxes.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/box_card.html.twig' as boxCard %}

{% block title %}
    Organizer: All Boxes
{% endblock %}

{% block body %}
<div class="container main-window">
    <div class="row mb-3 text-center">
        <div class="col">
            <h4>All Boxes</h4>
        </div>
    </div>
    <div class="row mb-3 text-left">
        <div class="col">
            <a class="btn btn-light" href="/">&lt; Back to Top</a>
        </div>
    </div>
    {% for row in boxes|batch(3, 'skip') %}
        <div class="row mb-3">
            {% for box in row %}
                <div class="col-md-12 col-lg-4">
                    {% if box != 'skip' %}
                        {{ boxCard.draw(box, true) }}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% apply spaceless %}{% block title %}Organizer{% endblock %}{% endapply %}</title>
        <link rel="icon" type="image/svg+xml" href="{{ asset('assets/fontawesome/dolly-solid-multicolor.svg') }}" />
        <link rel="apple-touch-icon" type="image/png" href="{{ asset('assets/fontawesome/dolly-solid-multicolor.png') }}" />
        <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
            integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
            crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('assets/organizer.css') }}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary mb-3 sticky-top" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ path('app_home') }}">Organizer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if app.user %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Boxes
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ path('app_box_all') }}">See All</a>
                                    <a class="dropdown-item" href="{{ path('app_box_recent') }}">See Recently Changed</a>
                                    <a class="dropdown-item" href="{{ path('app_box_new') }}">Add New</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Box Models
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ path('app_box_model_all') }}">See All</a>
                                    <a class="dropdown-item" href="{{ path('app_box_model_new') }}">Add New</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Locations
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ path('app_location_all') }}">See All</a>
                                    <a class="dropdown-item" href="{{ path('app_location_new') }}">Add New</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Bulk
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ path('app_export') }}">Export Data</a>
                                </div>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_about') }}">About</a>
                        </li>
                        {% if app.user %}
                            <li class="nav-item d-lg-none">
                                <a class="nav-link" href="{{ path('app_profile') }}">
                                    Change Your Password
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_login') }}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                    {% if app.user %}
                        <ul class="nav navbar-nav navbar-right me-3">
                            <li class="d-none d-lg-inline">
                                <a href="{{ path('app_profile') }}">
                                    <img src="{{ app.user.avatarUrl }}" class="avatar rounded-circle img-responsive" />
                                </a>
                            </li>
                        </ul>
                        <form class="d-lg-flex d-none" role="search" action="{{ path('app_box_search') }}" data-bs-theme="light">
                            <input class="form-control me-2 " type="search" placeholder="Search" aria-label="Search" name="q">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="container">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('error') %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        {% block body_full %}
            <div class="container main-window">
                {% block body_search %}
                    {% if app.user %}
                        <div class="row justify-content-center d-lg-none d-flex">
                            <div class="col mb-3">
                                <form class="form-inline" action="{{ path('app_box_search') }}">
                                    <div class="input-group">
                                        <input class="form-control me-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                                        <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search"></i></button>
                                        <a class="btn btn-outline-primary ms-4" href="{{ path('app_box_new') }}"><i class="fas fa-plus"></i></a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% endif %}
                {% endblock %}
                {% block body %}{% endblock %}
            </div>
        {% endblock %}
        <script
            src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js"
            integrity="sha384-5AkRS45j4ukf+JbWAfHL8P4onPA9p0KwwP7pUdjSQA3ss9edbJUJc/XcYAiheSSz"
            crossorigin="anonymous"></script>
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js"
            integrity="sha384-G/EV+4j2dNv+tEPo3++6LCgdCROaejBqfUeNjuKAiuXbjrxilcCdDz6ZAVfHWe1Y"
            crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/9471099de1.js" crossorigin="anonymous"></script>
        <script src="{{ asset('assets/organizer.js') }}"></script>
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/box_card.html.twig' as boxCard %}

{% block title %}
    Organizer
{% endblock %}

{% block body %}
    {% if recentBoxes is not empty %}
        <div class="row mb-3 justify-content-center">
            <div class="col d-grid">
                <a class="btn btn-primary-outline border border-primary rounded text-primary" href="{{ url('app_box_recent') }}" role="button">Recently Added or Changed</a>
            </div>
        </div>
        <div class="row mb-lg-3">
            {% for box in recentBoxes %}
                <div class="col-12 col-lg-4">
                    {% if box != 'skip' %}
                        {{ boxCard.draw(box, false, true) }}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row mb-3 justify-content-center">
        <div class="col d-grid">
            <a class="btn btn-primary-outline border border-primary rounded text-primary" href="{{ url('app_location_all') }}" role="button">Locations with Boxes</a>
        </div>
    </div>
    <div class="accordion">
        {% for location in locations %}
            {% set accordionTarget = 'children-' ~ location.id | e('html_attr') %}
            <div class="row mb-3">
                <div class="col d-grid">
                    <button class="btn btn-primary btn-accordion" type="button" data-bs-toggle="collapse" data-bs-target="#{{ accordionTarget }}">
                        {{ location.displayLabel }}
                    </button>
                </div>
            </div>
            <div class="container collapse accordionTarget" id="{{ accordionTarget }}">
                {% for row in location.getBoxes()|batch(3, 'skip') %}
                    <div class="row mb-lg-3">
                        {% for box in row %}
                            <div class="col-12 col-lg-4">
                                {% if box != 'skip' %}
                                    {{ boxCard.draw(box, false, true) }}
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock %}